dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "12"

env:
  - TEST=integration
  - TEST=colony
  - TEST=geth

matrix:
  fast_finish: true
  allow_failures:
    - env: TEST=colony
    - env: TEST=geth

script:
  - npm run ci
